FROM julia:1.8
WORKDIR /scheduler

# Install dependencies
COPY Manifest.toml  /scheduler/
COPY Project.toml /scheduler/
ENV JULIA_PROJECT=.
RUN julia -e 'using Pkg; Pkg.instantiate();'

# Install Scheduler source
COPY src/ /scheduler/src/
RUN julia -e 'using Pkg; Pkg.resolve();'
RUN julia -e 'using Pkg; Pkg.precompile();'

# Launch Scheduler
EXPOSE 8080
CMD [ "julia", "--threads",  "4", "-e", "using Scheduler; Scheduler.run!();" ]