FROM julia:1.9
WORKDIR /sciml-service

# Install SimulationService.jl
COPY Project.toml /sciml-service/
COPY Manifest.toml /sciml-service/
COPY src/ /sciml-service/src/
COPY examples/ /sciml-service/examples/
ENV JULIA_PROJECT=.
RUN julia -e 'using Pkg; Pkg.instantiate();'

# Launch sciml-service
EXPOSE 8080
CMD [ "julia", "--threads",  "4", "-e", "using SimulationService; SimulationService.start!(); while true sleep(10000) end" ]
