FROM julia:1.9
WORKDIR /simulation-service

# Install dependencies
COPY Manifest.toml  /simulation-service/
COPY Project.toml /simulation-service/
ENV JULIA_PROJECT=.
RUN julia -e 'using Pkg; Pkg.instantiate();'

# Install simulation-service source
COPY src/ /simulation-service/src/
RUN julia -e 'using Pkg; Pkg.resolve();'

# Launch simulation-service
EXPOSE 8080
CMD [ "julia", "--threads",  "4", "-e", "using SimulationService; SimulationService.start!(); while true sleep(10000) end" ]