---
    # Julia Tests

    name: SimulationService.jl Tests (Multi-threaded)
    on:
      push:
        branches: ['main']
      pull_request:

    jobs:
      test:
        env:
          JULIA_NUM_THREADS: 4
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: julia-actions/setup-julia@v1
            with:
              version: '1.10'
          - uses: julia-actions/cache@v1
            with:
              cache-compiled: "true"
          - uses: julia-actions/julia-buildpkg@v1
          - uses: julia-actions/julia-runtest@v1
          - uses: julia-actions/julia-processcoverage@v1
          - uses: codecov/codecov-action@v1
            with:
              file: lcov.info
          - uses: actions/upload-artifact@v3
            with:
              name: payloads
              path: test/logs/
